---
- hosts: localhost
  gather_facts: no
#  become: yes
#  vars:
#    - ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:

#    - name: execute parser
#      local_action: command /usr/bin/python /etc/fortigate/transform.py -i /etc/fortigate/response.json -o /etc/fortigate/parsedPolicy.csv


    - name: sort the vips to ensure they are unique
      shell: cat /etc/netscaler/parsedVIPs.csv | sort -u | uniq -u > /etc/netscaler/parsedVIPsUnique.csv
      delegate_to: localhost

    # the sorting to make unique move the headers of the csv.  
    # these net two tasks out it back at the top of the file.
    - name: delete the moved header
      lineinfile:
        path: /etc/netscaler/parsedVIPsUnique.csv
        regexp: '^(location,serialnbr,vdom,extip,mappedip)'
        state: absent
        # backup: yes
      run_once: yes
      delegate_to: localhost

    - name: insert the header back to the top of the file
      lineinfile:
        path: /etc/netscaler/parsedVIPsUnique.csv
        line: 'location,serialnbr,vdom,extip,mappedip'
        insertbefore: BOF 
      run_once: yes
      delegate_to: localhost

    - name: Read data from CSV file and return a list
      read_csv:
        path: /etc/netscaler/parsedVIPsUnique.csv
      register: vips
      delegate_to: localhost

    # before processing, create the base csv file
    - name: create the base csv file
      lineinfile:
        dest: /etc/netscaler/netboxImport.csv
        line: "cf_device_location,name,cf_vdom,cf_extip,cf_mappedip,device_role,manufacturer,device_type,status,site,cf_lbvservername,cf_lbvserverip,cf_lbvipserver_currstatus,cf_servicegroupname,cf_servicegroup_member,cf_servicegroup_member_ip"
        create: yes
      run_once: yes

    - name: Loop through the Vips, get lbvserver info
      include_tasks: lbvserver.yml
      with_items: "{{ vips.list }}"



    # - name: Define Values From CSV File, this reads file in one go, but you could also use col= to read each in it's own lookup.
    #   set_fact:
    #     loop_ip: "{{ csvline[0] }}"
    #     int_ip: "{{ csvline[1] }}"
    #     int_mask: "{{ csvline[2] }}"
    #     int_name: "{{ csvline[3] }}"
    #     local_as: "{{ csvline[4] }}"
    #     neighbor_as: "{{ csvline[5] }}"
    #     neigh_int_ip: "{{ csvline[6] }}"
    #   vars:
    #     csvline = "{{ lookup('csvfile', bgp_neighbor_ip, file='parsedVIPsUnique.csv', delimiter=',') }}"
    #   delegate_to: localhost

    # - name: use sed to append data
    #   command:  sed '/CA-NEW-C.INGRAMMICRO.COM_HTTP/ s/$/,data,moredata/' /etc/netscaler/appendSample.csv
    #   delegate_to: localhost 

    # - name: line insert
    #   lineinfile:
    #     path: /etc/netscaler/appendSample.csv
    #     backrefs: yes
    #     regexp: "(.*CA-NEW-C.INGRAMMICRO.COM_HTTP.*)$"
    #     line: '\1,Ijustaddedthis' 
    #   run_once: yes
    #   delegate_to: localhost