---
- hosts: localhost

  tasks:
  - name: Get py version
    command: /usr/bin/python3 --version

  - name: execute parser
    local_action: 
#      module: command /usr/bin/python3 /var/lib/awx/projects/_13__ingram/parsePolicy.py -i /tmp/policy.json -o /tmp/parsedPolicy.csv
#    ansible.builtin.command: /usr/bin/python3 /tmp/transform.py -i /tmp/response.json -o /tmp/parsedPolicy.csv
      script: 
        chdir: /tmp
        cmd: ./helloworld.sh
        creates: helloworld.sh
 #   delegate_to: localhost