---
- hosts: localhost
  become: yes

  tasks:
  - name: Get py version
    command: /usr/bin/python3 --version

  - name: execute parser
#  - local_action: 
#    command: /usr/bin/python3 /tmp/transform.py -i /tmp/response.json -o /tmp/parsedPolicy.csv
    command: echo /tmp/response.json
#      module: script /tmp/helloworld.sh
