---
- hosts: localhost
  gather_facts: no
#  vars:
#    - ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:

    - name: execute parser
      local_action: command /usr/bin/python /etc/fortigate/transform.py --ifile /etc/fortigate/response.json -ofile /etc/fortigate/parsedPolicy.csv
