---
- hosts: localhost
  gather_facts: no


  tasks:
    - name: Get py version
      command: /usr/bin/python3 --version

    - name: execute parser
      local_action: command /usr/bin/python3 /etc/fortigate/transform.py --ifile /etc/fortigate/response.json -ofile /etc/fortigate/parsedPolicy.csv
